import 'package:flutter/material.dart';

class LocalizationService extends ChangeNotifier {
  String _currentLocale = 'uz'; // 'uz', 'ru', 'en'

  String get currentLocale => _currentLocale;

  void setLocale(String locale) {
    if (['uz', 'ru', 'en'].contains(locale)) {
      _currentLocale = locale;
      notifyListeners();
    }
  }

  static final Map<String, Map<String, String>> _localizedValues = {
    'uz': {
      'app_title': 'Quiz Duel',
      'level': 'Daraja',
      'rating': 'Reyting',
      'weekly_tournament': 'Haftalik Turnir',
      'prize_pool': 'Sovrin Fondi: 2 000 000 UZS',
      'tournament_desc': 'Duellarda g\'alaba qozoning va TOP-3 da sovrinli o\'rinlarni egallang!',
      'view_leaderboard': 'Reytingni Ko\'rish',
      'ends_in': 'Yakunlanadi: 2k 14s',
      'start_duel': '1v1 TASODIFIY DUEL',
      'duel_desc': 'Raqib bilan 5 ta savolda bellashuv (-1 Energiya)',
      'play_with_friend': 'Do\'st bilan bellashuv',
      'play_with_friend_desc': 'Xona ochish yoki kod orqali ulanish',
      'daily_quests': 'Kunlik Topshiriqlar',
      'login_streak': 'Kunlik Kirish Bonusi',
      'claim': 'Olish',
      'claimed': 'Olingan',
      'shop_vip': 'Do\'kon & VIP',
      'shop_vip_desc': 'Tanga, Jon va VIP Pass',
      'leaderboard': 'Peshqadamlar',
      'leaderboard_desc': 'Top-100 O\'yinchilar',
      'searching_opponent': 'Raqib qidirilmoqda...',
      'searching_desc': 'Sizning darajangizga mos o\'yinchi tanlanmoqda',
      'cancel': 'Bekor qilish',
      'energy_depleted': 'Energiya tugadi! Do\'kondan xarid qiling yoki kuting.',
      'ball': 'ball',
      'booster_5050': '50/50',
      'booster_time': '+5 Soniya',
      'explanation': 'Izoh',
      'victory': 'G\'ALABA!',
      'draw': 'DURRANG!',
      'defeat': 'MAG\'LUBIYAT',
      'coins_won': 'Yutilgan Tangalar',
      'rating_pts': 'Reyting Ballari (MMR)',
      'xp_won': 'Tajriba (XP)',
      'return_home': 'Bosh Sahifaga Qaytish',
      'vip_pass_title': 'VIP PASS OBUNASI',
      'vip_features': '✓ Butunlay reklamasiz o\'yin\n✓ Cheksiz energiya (20 jon)\n✓ 2x Tanga va Tajriba bonuslari\n✓ Oltin profil ramkasi va VIP unvoni',
      'vip_subscribe': '39 000 UZS / Oyiga Ulanish',
      'coins_lives': 'Tangalar va Jonlar',
      'rank_1_prize': '1-o\'rin: 1 000 000 UZS',
      'rank_2_3_prize': '2-o\'rin: 500 000 UZS • 3-o\'rin: 250 000 UZS',
      'rank_top_prize': 'Top 4-10: 1 Oylik VIP Pass bepul',
      'select_lang': 'Tilni tanlang',
      'create_room_title': 'Do\'stni Duelga Chaqirish',
      'room_code': 'Xona kodi',
      'share_code': 'Kodni do\'stingizga yuboring',
    },
    'ru': {
      'app_title': 'Quiz Duel',
      'level': 'Уровень',
      'rating': 'Рейтинг',
      'weekly_tournament': 'Еженедельный Турнир',
      'prize_pool': 'Призовой Фонд: 2 000 000 UZS',
      'tournament_desc': 'Побеждайте в дуэлях и занимайте призовые места в ТОП-3!',
      'view_leaderboard': 'Смотреть Рейтинг',
      'ends_in': 'Осталось: 2д 14ч',
      'start_duel': '1v1 СЛУЧАЙНАЯ ДУЭЛЬ',
      'duel_desc': 'Битва с соперником из 5 вопросов (-1 Энергия)',
      'play_with_friend': 'Игра с другом',
      'play_with_friend_desc': 'Создать комнату или войти по коду',
      'daily_quests': 'Ежедневные Задания',
      'login_streak': 'Бонус за вход',
      'claim': 'Забрать',
      'claimed': 'Получено',
      'shop_vip': 'Магазин и VIP',
      'shop_vip_desc': 'Монеты, Жизни и VIP Pass',
      'leaderboard': 'Лидеры',
      'leaderboard_desc': 'Топ-100 Игроков',
      'searching_opponent': 'Поиск соперника...',
      'searching_desc': 'Подбираем игрока вашего уровня',
      'cancel': 'Отмена',
      'energy_depleted': 'Энергия закончилась! Купите в магазине или подождите.',
      'ball': 'очков',
      'booster_5050': '50/50',
      'booster_time': '+5 Секунд',
      'explanation': 'Объяснение',
      'victory': 'ПОБЕДА!',
      'draw': 'НИЧЬЯ!',
      'defeat': 'ПОРАЖЕНИЕ',
      'coins_won': 'Получено монет',
      'rating_pts': 'Очки рейтинга (MMR)',
      'xp_won': 'Опыт (XP)',
      'return_home': 'На Главную',
      'vip_pass_title': 'ПОДПИСКА VIP PASS',
      'vip_features': '✓ Игра без рекламы\n✓ Неограниченная энергия (20 жизней)\n✓ 2x Монеты и Опыт\n✓ Золотая рамка профиля и VIP статус',
      'vip_subscribe': '39 000 UZS / Месяц',
      'coins_lives': 'Монеты и Жизни',
      'rank_1_prize': '1-е место: 1 000 000 UZS',
      'rank_2_3_prize': '2-е: 500 000 UZS • 3-е: 250 000 UZS',
      'rank_top_prize': 'Топ 4-10: 1 Месяц VIP Pass бесплатно',
      'select_lang': 'Выберите язык',
      'create_room_title': 'Пригласить друга на дуэль',
      'room_code': 'Код комнаты',
      'share_code': 'Отправьте код другу для подключения',
    },
    'en': {
      'app_title': 'Quiz Duel',
      'level': 'Level',
      'rating': 'Rating',
      'weekly_tournament': 'Weekly Tournament',
      'prize_pool': 'Prize Pool: 2,000,000 UZS',
      'tournament_desc': 'Win duels and claim prize spots in the TOP 3!',
      'view_leaderboard': 'View Leaderboard',
      'ends_in': 'Ends in: 2d 14h',
      'start_duel': '1v1 RANDOM DUEL',
      'duel_desc': '5-question battle against an opponent (-1 Energy)',
      'play_with_friend': 'Play with a Friend',
      'play_with_friend_desc': 'Create room or join with a code',
      'daily_quests': 'Daily Quests',
      'login_streak': 'Daily Login Streak',
      'claim': 'Claim',
      'claimed': 'Claimed',
      'shop_vip': 'Shop & VIP',
      'shop_vip_desc': 'Coins, Lives & VIP Pass',
      'leaderboard': 'Leaderboard',
      'leaderboard_desc': 'Top 100 Players',
      'searching_opponent': 'Searching for opponent...',
      'searching_desc': 'Matching with a player of your skill level',
      'cancel': 'Cancel',
      'energy_depleted': 'Out of energy! Refill in shop or wait.',
      'ball': 'pts',
      'booster_5050': '50/50',
      'booster_time': '+5 Seconds',
      'explanation': 'Explanation',
      'victory': 'VICTORY!',
      'draw': 'DRAW!',
      'defeat': 'DEFEAT',
      'coins_won': 'Coins Won',
      'rating_pts': 'Rating Points (MMR)',
      'xp_won': 'Experience (XP)',
      'return_home': 'Return to Home',
      'vip_pass_title': 'VIP PASS SUBSCRIPTION',
      'vip_features': '✓ 100% Ad-Free Experience\n✓ Unlimited Energy (20 Lives)\n✓ 2x Coins and XP Multiplier\n✓ Golden Profile Frame & VIP Badge',
      'vip_subscribe': '39,000 UZS / Month',
      'coins_lives': 'Coins & Lives',
      'rank_1_prize': '1st Place: 1,000,000 UZS',
      'rank_2_3_prize': '2nd: 500,000 UZS • 3rd: 250,000 UZS',
      'rank_top_prize': 'Top 4-10: 1 Month Free VIP Pass',
      'select_lang': 'Select Language',
      'create_room_title': 'Invite a Friend to Duel',
      'room_code': 'Room Code',
      'share_code': 'Send this code to your friend to play',
    },
  };

  String text(String key) {
    return _localizedValues[_currentLocale]?[key] ?? _localizedValues['uz']?[key] ?? key;
  }
}
